### ISSUE TITLE
vim.org

### ISSUE THREAD

**Issue by bramswenson** [wikimatze/hammer.vim#20]
Please add your script to vim.org. This will allow vim-scripts.org to scrape it, prep it for use with pathogen, which will then allow me to use it via [vimpack](http://github.com/bramswenson/vimpack)

**Comment by ghost** [comment]
I don't really want to have to maintain a release on _vim.org_. 
If someone else would like to volunteer and **maintain** releases on _vim.org_, they're more then welcome to.

If someone volunteers, I'll talk to them about a release schedule, since right now hammer is more like a rolling release and probably not a good idea if we decide to publish on _vim.org_.

**Comment by bramswenson** [comment]
I completely understand. In the future I may volunteer to maintain hammer.vim releases on vim.org. However, this really is a good catalyst for me to add the "install via git repo" feature to vimpack. Thanks for the info.
